Traceback (most recent call last):
  File "/home/phuijse/.conda/envs/info183/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/phuijse/.conda/envs/info183/lib/python3.8/site-packages/nbclient/client.py", line 1082, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/phuijse/.conda/envs/info183/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/phuijse/.conda/envs/info183/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/home/phuijse/.conda/envs/info183/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/phuijse/.conda/envs/info183/lib/python3.8/site-packages/nbclient/client.py", line 535, in async_execute
    await self.async_execute_cell(
  File "/home/phuijse/.conda/envs/info183/lib/python3.8/site-packages/nbclient/client.py", line 827, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/phuijse/.conda/envs/info183/lib/python3.8/site-packages/nbclient/client.py", line 735, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Espectrograma de una sinusoide pura y de una sinusoide modulada (tremolo y vibrato)
plt.close('all'); fig, ax = plt.subplots(2, figsize=(8, 6))
sample_rate = 44100; time = np.arange(0, 3, step=1.0/sample_rate)
noise = 0.0*np.random.randn(len(time))
mod_am = 1.0 # 0.25 + (1.0 + np.cos(2*np.pi*4*time))*0.75
mod_fm = 20*np.cos(2.*np.pi*8*time);
phase_fix = np.add.accumulate(time*np.concatenate((np.zeros(1), 2*np.pi*(mod_fm[:-1]-mod_fm[1:]))))
data = mod_am*np.sin(2.*np.pi*(220 + mod_fm)*time + phase_fix) + noise
ax[0].plot(time, data); 
freq, ttime, Sxx = scipy.signal.spectrogram(data, fs=sample_rate, window=('tukey', 0.25), 
                                            nperseg=256, noverlap=None, detrend=False,
                                            return_onesided=True, scaling='density', mode='magnitude')
ax[1].pcolormesh(ttime, freq, np.log10(Sxx + 1e-5), cmap=plt.cm.magma); #ax[1].set_ylim([0., 5e+3]) 
Audio(data, rate=sample_rate)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-2-6006925b8548>[0m in [0;36m<module>[0;34m[0m
[1;32m     12[0m                                             return_onesided=True, scaling='density', mode='magnitude')
[1;32m     13[0m [0max[0m[0;34m[[0m[0;36m1[0m[0;34m][0m[0;34m.[0m[0mpcolormesh[0m[0;34m([0m[0mttime[0m[0;34m,[0m [0mfreq[0m[0;34m,[0m [0mnp[0m[0;34m.[0m[0mlog10[0m[0;34m([0m[0mSxx[0m [0;34m+[0m [0;36m1e-5[0m[0;34m)[0m[0;34m,[0m [0mcmap[0m[0;34m=[0m[0mplt[0m[0;34m.[0m[0mcm[0m[0;34m.[0m[0mmagma[0m[0;34m)[0m[0;34m;[0m [0;31m#ax[1].set_ylim([0., 5e+3])[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 14[0;31m [0mAudio[0m[0;34m([0m[0mdata[0m[0;34m,[0m [0mrate[0m[0;34m=[0m[0msample_rate[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;31mNameError[0m: name 'Audio' is not defined
NameError: name 'Audio' is not defined

